### ISSUE TITLE
Реализовать реагирование на вебхуки

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#1]
В дальнейшем планируется выстроить работу на вебхуках. Нужно изучить что мы можем оттуда получить и как. Пока кажется, что нам нужно реагировать на:
- Создание PR
- Добавление комита
- Добавелине ревью
- Добавление коммента

**Comment by lipa44** [comment]
> скопирую описание таски на гит

Т.к. нам надо не только слушать события, но и писать ответы (айдишник сабмишена для последующего редактирования, возможно при ошибке тоже хотим что-то писать), то нам нужен [[github app](https://docs.github.com/en/developers/apps)](https://docs.github.com/en/developers/apps)

От его имени будут писаться сообщения, и к самому приложению можно подвязать вебхук точно так же, как к репозиторию/орге

Со стороны гитхаба все это я могу создать уже сейчас - в хуке нам надо будет слушать pull request и issue comments (для комманд в пре) 

Непосредственно по написанию кода:

[https://github.com/octokit/octokit.net/blob/main/docs/github-apps.md](https://github.com/octokit/octokit.net/blob/main/docs/github-apps.md)

У аппов не совсем простой способ авторизации

Сначала нужно создать jwt-токен (на это даже написали библиотеку, есть в ридми по ссылке выше), а потом запросить installation токен, который еще и придется регулярно перезапрашивать (это нам реализовывать самим) 

По поводу самих вебхуков

[https://github.com/octokit/octokit.net/blob/main/docs/github-apps.md](https://github.com/octokit/octokit.net/blob/main/docs/github-apps.md)

Кажется здесь уже все максимально реализовано за нас

**Comment by lipa44** [comment]
> Добавление коммента

Коммент и РевьюКоммент - это разные вещи, на что именно мы хотим реагировать?

**Comment by darksidersstrife** [comment]
Просто IssueComment, в ревью скорее будет писаться про сам код
