### ISSUE TITLE
Тестовое окружение для запуска приложения

### ISSUE THREAD

**Issue by darksidersstrife** [kysect/Shreks#101]
Сейчас для работы гитхаб плейграунда нужна заполненная база
В ней должно быть:
1) Тестовые предмет и курс
2) Ассоциация с организацией (берем из конфига)
3) Тестовая лаба (для нее какое-нибудь захардкоженное (или из конфига) short name)
4) Тестовые юзеры, ассоциированные с гитхабом (берем ники гх из конфига и создаем по ним)
5) Хорошо бы, чтобы тестовые юзеры (мы) были и студентами, и менторами (по идее от такого ничего не сломается)

**Comment by FrediKats** [comment]
close #112
