### ISSUE TITLE
Продумать форкфлоу создания гугл таблицы

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#102]
Наша интеграция подразумевает написание в гугл таблицы данных, но не ясно когда и кто будет создавать. Есть два варианта:

1. Создавать будет юзер. Тогда нужно уметь ссылки прокидывать в базу + он должен быть уверен, что он дал пермишены боту на запись.
2. Создавать будет система. Тогда нужно определиться с тем, в какой момент она это будет делать.

Мне больше нравится второй вариант т.к. заставлять пользователя делать лишние вещи смысла нет, а логика прокидывания ссылки в систему из-вне будет не оч приятная учитывая, что у нас нет авторизации.

**Comment by Mihinator3000** [comment]
Можно так то при обновлении листов смотреть, что существует ассоциация с таблицей, если нет, то создавать
