### ISSUE TITLE
Возвращать из GetCoursePointsBySubjectCourseHandler результат по каждому assignment'у

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#126]
Сейчас в GetCoursePointsBySubjectCourseHandler если у студента нет никаких ассайментов, то будет возвращаться пустота. Но мы ожидаем, что по каждому ассайменту вернётся результат, чтобы на фронте его было проще отрисовать и не проверять пропущено ли что-то.

**Comment by Mihinator3000** [comment]
Так это специально сделано, либа Гоши под такое и написана

**Comment by Mihinator3000** [comment]
> как отработает рендеринг, если я сдал только первую и третью домашку? Там не сломается порядок? Я только поэтому написал.

> Суть изменений в том, что мы хотим рисовать "0", если стоит 0 баллов и ничего не рисовать, если ничего не поставили. Это разные значения.

Все в принципе нормально и работало без уже замерженного #127, можно посмотреть на примере таблицы https://github.com/kysect/Shreks/blob/master/Docs/GoogleIntegration.md

Ноль также пишется, если есть сабмишен на 0 баллов, если сабмишенов не было, то пустота. Только теперь мы аллоцируем память на ненужные объекты.

Вообще не вижу смысла в изменении того, что было

**Comment by FrediKats** [comment]
Не понял про какие аллокации идёт речь.

**Comment by Mihinator3000** [comment]
Ну по идее, что мы должны всегда создавать AssignmentPointsDto, даже если за лабу ничего не ставилось

**Comment by FrediKats** [comment]
А, хм. Теперь понял. Если это учитывается, то тогда действительно смысла не особо много.

**Comment by Mihinator3000** [comment]
Окей, я бы тогда ревертнул все изменения #127, связанные с таблицами и закрыл эту ишью

**Comment by Mihinator3000** [comment]
@FrediKats так что
