### ISSUE TITLE
Обработать ситуации, когда пользователь создаёт второй PR на ассаймент

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#136]
Студент мог создать PR, после чего система его регистрирует. После он закрывает PR (например, случайно мёрджит в мастер). Нужно дать возможность без болезненно создать новый PR и там начать с 0. Один из вариантов - помечать старые не оцененные submission как outdated и их фильтровать при операциях.

**Comment by annchous** [comment]
Нужно ещё проверить возможность переоткрытия пулл-реквеста после мёрджа/закрытия. Если студент замёрджил/закрыл пулл-реквест случайно, то можно попросить его переоткрыть его, чтобы преподавателю было удобнее смотреть.
