### ISSUE TITLE
CQRS

### ISSUE THREAD

**Issue by darksidersstrife** [kysect/Shreks#14]
1) Резолвинг гх никнейм -> юзер
2) Резолвинг гх организация -> курс
3) Из имени ветки (префикс) и курса получить лабораторную*
4) Добавление сабмишена (id юзера, id лабораторной, ссылка на пр)
5) Изменение даты сабмишена (id юзера, id лабораторной, дата)
6) Изменение пр сабмишена (id юзера, id лабораторной, ссылка на пр)
7) Изменение оценки сабмишена (id юзера, id лабораторной, баллы)

*Сейчас у лабораторной только title, нужно что-то типа short name, который будет префиксом ветки

**Comment by Bibletoon** [comment]
> Изменение даты сабмишена (id юзера, id лабораторной, дата)
Изменение пр сабмишена (id юзера, id лабораторной, ссылка на пр)
Изменение оценки сабмишена (id юзера, id лабораторной, баллы)

У нас же у одной пары лабораторная + юзер может быть много сабмишенов, так что для редактирования нужно принимать Id конкретного сабмишена
