### ISSUE TITLE
Обработать ситуацию ручного форса обработки pull-request'а

### ISSUE THREAD

**Issue by annchous** [kysect/Shreks#147]
Если студент пропустил этап с авторизацией в системе Shreks'а через GitHub и уже открыл pull-request с выполненной работой, нужно иметь возможность вручную зафорсить обработку такого pr системой (после того, как он всё-таки пройдёт авторизацию и попадёт в базу), например через команду.

Если студент закоммитит что-то ещё после авторизации, то проблем с созданием submission'а возникнуть не должно, но если коммитов не будет, то Shreks'у будет не на что триггериться.

**Comment by FrediKats** [comment]
Давайте всё таки добавим команду /create-submission, которая создаёт, если не создан. Не нужно только переиспользовать CreateOrUpdate т.к. обновлять нам не нужно. Если сабмишен текущий уже создан - нужно кинуть ошибку.
