### ISSUE TITLE
Проработать воркфлоу добавления гугл токена и его рефреш

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#152]
Нужно посмотреть, как можно закинуть в систему гугл токен и как заставить его рефрешиться.

**Comment by Mihinator3000** [comment]
Нужно подумать насколько важно создание таблиц для курса автоматически, потому что само редактирование может быть произведено полностью через Sheets API, в котором можно использовать сервис аккаунты не требующие рефреш и пользователя

**Comment by Mihinator3000** [comment]
Если конечно можно сделать рефреш более-менее автоматически без возможных проблем, я скорее за автосоздание (Не зря же я его настраивал часов 6 :))

**Comment by ronimizy** [comment]
Пользователь нужен энивей. Мы же не создаём таблицы для публичного редактирования.

**Comment by ronimizy** [comment]
> Если конечно можно сделать рефреш более-менее автоматически без возможных проблем, я скорее за автосоздание (Не зря же я его настраивал часов 6 :))

Да наверняка, я там видел метод похожий на то, что нужно

**Comment by Mihinator3000** [comment]
Ну можно сервис аккаунт по емейлу добавить, только он сможет редактировать

**Comment by ronimizy** [comment]
> Ну можно сервис аккаунт по емейлу добавить, только он сможет редактировать

Поинт в том, что аутентификацию пройти надо всё равно

**Comment by Mihinator3000** [comment]
В каком смысле? С кредами сервис аккаунта просто так запускалось всегда

**Comment by ronimizy** [comment]
> В каком смысле? С кредами сервис аккаунта просто так запускалось всегда

Ну это да, аутентификацию под сервис аккаунтом. Пользователь нам всё равно нужен, чтобы у него создавать файлы.

**Comment by ronimizy** [comment]
По идее можно сделать шаренную папку с сервис аккаунтом, и тогда апи разрешит в ней от его лица создавать файлы

**Comment by ronimizy** [comment]
По рефрешу, есть метод `GoogleWebAuthorizationBroker.ReauthorizeAsync`

**Comment by ronimizy** [comment]
можно либо оборачивать в трай кетч вызовы апи и рефрешить креды, либо завести бекграунд воркер который будет это делать раз в интервал

второй вариант мне нравится больше, но надо поресёрчить насчёт того какое время жизни у кредов

**Comment by Mihinator3000** [comment]
А когда мы метод этот вызывать должны? Раз в неделю и потом закидывать токен на сервер? Или там как-то попроще?

**Comment by ronimizy** [comment]
Раз в неделю и потом закидывать токен на сервер?

Не, у тебя же по секретам генерится токен, сохраняется в "token.json" (ну, потому что он так назван), ты этим методом просто регенеришь "token.json" ну и инмемори креды.

Так что ничего на сервер закидывать не надо, только в изначальную конфигурацию креды

**Comment by Mihinator3000** [comment]
Ну просто вот..
![image](https://user-images.githubusercontent.com/70411602/185804717-b81c8c83-e6d0-49f0-9635-f87505afdbf6.png)

**Comment by ronimizy** [comment]
Хм, для сервис аккаунтов мб даже рефреш не нужен

https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth#service-account

**Comment by Mihinator3000** [comment]
Я знаю, их и активировать не надо, но драйв api от него я не смог сделать

**Comment by ronimizy** [comment]
https://www.labnol.org/google-api-service-account-220404

**Comment by Mihinator3000** [comment]
Окей, попробую сделать
