### ISSUE TITLE
Прописать команды для выставления баллов

### ISSUE THREAD

**Issue by darksidersstrife** [kysect/Shreks#16]

**Comment by darksidersstrife** [comment]
Для выставления баллов (и в целом взаимодействия с сабмишенами) будут использоваться команды в pr

1) /assess процент [доп баллы]
Проставление текущему сабмишену оценки в процентах от maxPoints для лабы + доп баллы как абсолютное значение
2) /update submission-id (процент [доп баллы]) | дата
Обновляет оценку или дату сабмишена

Над неймингом можно поработать)0

**Comment by ronimizy** [comment]
>    Проставление текущему сабмишену оценки в **процентах** от maxPoints для лабы + доп баллы как абсолютное значение

Чисто теоретически можно добавить возможность писать баллы в виде "N" или "N%", где первое будет восприниматься как абсолютное число, а второе как процентное. Но для этого надо будет отдельные команды делать будет, ну и сама фича не особо важная и насущная. Прост чтобы была идея что такое можно сделать (кмк прикольно).
