### ISSUE TITLE
Более подробно описывать результат оценивания

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#173]
Нужно в ответе бота на команду оценивания или апдейта оценки/даты указывать:

1. Рейт и балл с учётом только рейтинга
2. Размер бонусных баллов
3. Дату сдачи и размер штрафа за дедлайн, если есть
4. Итоговый балл, который попадёт в таблицу

Blocked by:

-  #202

**Comment by annchous** [comment]
А что сейчас указывается?
