### ISSUE TITLE
Добавить сабмишену стейт - active \ inactive

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#175]
Нужно добавить сабмишену стейты, чтобы в дальнейшем можно было реализовать логику их переключения. Это аффектит попадание в очередь. Соответственно нужно заодно добавить в очереди фильтр inactive сабмишенов.

**Comment by ronimizy** [comment]
Думаю можно сразу добавить `invalid` стейт, для того чтобы в будущем обрабатывать упавший ci.
