### ISSUE TITLE
В таблице с баллами сортировка выводит 1 10 2

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#184]
На странице с баллами сейчас выглядит что-то вот так:
![image](https://user-images.githubusercontent.com/22368203/186491540-9562f9a8-1778-4630-a5a8-3834ca1a572d.png)

**Comment by Mihinator3000** [comment]
С этим надо что-то делать? Могу пытаться найти int в shortname, если допустим он labN и по нему сортировать

**Comment by FrediKats** [comment]
Я думаю, что лучше всё же просто нумерацию добавить лабам. Чтобы в лабе хранилась инфа о том, какая она по порядку идёт.

**Comment by Mihinator3000** [comment]
А для чего тогда shortname нужен?

**Comment by FrediKats** [comment]
Мы по нему мапим названия веток же.

**Comment by Mihinator3000** [comment]
Типа labN как названия ветки или там будут разные варианты? Просто в первом случае название ветки зависит от номера лабы и хранить это как две разные переменные странно

**Comment by FrediKats** [comment]
Оставить возможность преподавателю указывать названия веток произвольные. Хочет lab-1, lab-2, lab-3 - ок. Решил запушить isu, shop, etc - ок. Но отдельно задавать будет индксы, чтобы правильно отсортировать у себя.
