### ISSUE TITLE
Не удаляется студент из очереди после того, как он оценён

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#185]
После оценки сабмишен он может оставаться в очереди. Он должен удаляться т.к. уже оценён.

**Comment by Mihinator3000** [comment]
Не очень понял почему у нас это отдельная ишью, у нас самой логики очереди как таковой не реализовано еще

**Comment by FrediKats** [comment]
🤔 
Тогда предлагаю собраться и обсудить.

**Comment by Mihinator3000** [comment]
Вроде уже не актуально
