### ISSUE TITLE
Проверять, что у юзера есть какая-то связь с текущей организацией

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#190]
Сейчас нет никаких валидаций на то, что студент имеет права в орге. Например, он может быть добавлен как ментор в курс А, но является студентом курса Б. Как итог, проверкой на существование мы получим, что он является студентов. Но нам нужно во всяких CreateSubmission проверять, что студент есть и что он является студентом данного курса.

**Comment by annchous** [comment]
И студент, являясь ментором на курсе Б, не сможет в курсе Б оценить сабмишен? Только в этом проблема?

**Comment by FrediKats** [comment]
В этом и проблема, да. Нужно убедиться, что у нас проверяется принадлежность текущему курсу. И что менторство относительно текущего курса.

**Comment by annchous** [comment]
Тут по-хорошему сначала сделать бы #137

**Comment by annchous** [comment]
Сейчас мы проверяем то, что пользователь является студентом просто поиском по таблице студентов. Если там этот студент нашёлся - значит он студент. Но при этом он может оказаться студентом другого курса, а на том курсе, что мы проверяли, он может быть ментором.

Нужно проверять студента с учётом принадлежности к данному SubjectCourse.

**Comment by hrrrrustic** [comment]
Решили, что это практически тоже самое, что и #137 и проще мне заодно сделать

**Comment by FrediKats** [comment]
Смёрджил в #137
