### ISSUE TITLE
Не создавать стандартный Sheet и заменять его на баллы

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#199]
Сейчас при создании документа, создаётся дефолтный Sheet1, который не нужен. Его нужно удалять. Также при генерации можем получить не тот порядок таблиц, который хотелось бы. Нам важнее баллы чем очередь. Ожидается, что будет сначала таблица с баллами, а потом таблицы с очередями по каждой группе, которые отсортированы по названию (!).

Как вариант была озвучена идея по переименованию Sheet1 сразу в баллы.

**Comment by Mihinator3000** [comment]
Про сорт по названию не обещаю, там можно только позиции листам давать
