### ISSUE TITLE
Использовать пересчёт баллов с учётом дедлайнов перед выводом на гитхаб и гугл

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#202]
На данный момент при оценивании работы ментором, сервис отвечает и пишет информацию о том, сколько баллов было выставлено, но он не учитывает дедлайн. Аналогичная ситуация с выводом на гугл таблицы - там нет снижения баллов за дедлайны, а выводятся только поинты с учётом рейтинга.

**Comment by Mihinator3000** [comment]
Ну вообще при выставлении в таблицы DeadlinePolicy вроде применяется на баллы
