### ISSUE TITLE
Ошибка при сохранении DeadlinePolicy со спаном больше чем сутки

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#229]
Шарповый TimeSpan мапиться на SQL Time тип у которого рендж значений от 0 до 23 часов. Как итог, сохраняя значение в N дней, мы получаем ошибку в SQL. Нужно подшаманить и зафорсить мапинг на какой-то другой SQL тип.

**Comment by ronimizy** [comment]
Можно просто конвержн а Ticks написать
