### ISSUE TITLE
Добавить сабмишен с пулл реквестом

### ISSUE THREAD

**Issue by darksidersstrife** [kysect/Shreks#26]
Сейчас в сабмишене нет собственно никакой полезной нагрузки - что именно отправил студент на проверку
Кажется, что на первое время можно обойтись простым текстовым полем - более того, оно сразу же подходит как сабмишен с текстовым ответом и для отправки файлов (ссылка на облако)

**Comment by Bibletoon** [comment]
В https://github.com/kysect/Shreks/pull/28/commits/441c884dc1d7ba3920abc432d08826814cc78cf9 были добавлены не до конца реализованные команды, для реализации которых необходим сабмишен с пулреквестом. После его добавления стоит заимплементить команды
