### ISSUE TITLE
Добавить страницу с саммари по баллам

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#280]
Нужно генерировать помимо таблицы со всеми баллами также и саммари, где будет краткая сводка:

![image](https://user-images.githubusercontent.com/22368203/188223312-7ddf26b4-240f-49f4-b8ef-df452b457ec8.png)

Ожидаемые столбцы:

- ИСУ
- ФИО
- Группа
- Лабы
- Бонусы
- Экзамен
- Оценка (?)
- Комментарий

**Comment by Mihinator3000** [comment]
Не очень понятно откуда брать комментарий и как определять оценку. Также вопрос, экзамен же вроде не является лабой, баллы откуда брать? В теории можно его оставить для заполнения преподавателем, но тогда Sum надо будет по формуле считать.
И еще, может лист `Баллы` в `Лабораторные` переименовать, а этот `Баллы` назвать?

**Comment by FrediKats** [comment]
Ой, я не дописал описание.

Да, эта страница как раз планируется как "сгенерировать один раз и подтянивать через ВПР".

**Comment by Mihinator3000** [comment]
По поводу сгенерировать 1 раз, это уже перед экзаменом? Просто так то лабораторные могут меняться и не ясно в какой ячейке будут баллы за них лежать, еще у нас нет столбца под доп баллы, они к лабам суммируются, но это поправимо

**Comment by FrediKats** [comment]
Ну, мы можем поправить его перед экзом, да. Сгенерить можно сразу. Формулы может даже и руками прописать и протянуть, там простая оч формула.
