### ISSUE TITLE
500 при удалении студента

### ISSUE THREAD

**Issue by ronimizy** [kysect/Shreks#306]
Эндпоинт на удаление студента (с существующим id) кидает ошибку 500

**Comment by FrediKats** [comment]
Проблема в FK - "update or delete on table "Students" violates foreign key constraint "FK_Submissions_Students_StudentUserId" on table "Submissions".

Предложение - удалить этот эндпоинт, а артефакты руками SQL запросами чистить. Операция удаления очень нежелательна в нашей системе.
