### ISSUE TITLE
Создать продакшн `GitHub App` от лица секты

### ISSUE THREAD

**Issue by lipa44** [kysect/Shreks#31]
- [x] Создать основную гитхаб апу от лица организации (нужны **права админа** в организации)
- [x] Настроить вебхуки, которые мы хотим хендлить
- [x] Создать `SecretKey` для апы _(для авторизации при создании клиента гита)_
- [x] Скачать `.pem` файл со вторым секретным ключом и расшарить его тем, кто зап ускает хост интеграции с гитом _(без него хендлинг модуль тоже не пройдёт авторизацию и не сможет обрабатывать хуки)_
- [x] Поставить мемного шрека на аву апы

P.S. `SecretKey` нужно будет прокинуть в `appsetings.json` тестового хоста или придумать, где мы его будет хранить. `.pem` файл нужно будет подкинуть в корень проекта хоста

**Comment by FrediKats** [comment]
Оруг сделал - https://github.com/is-prog-y26.
Права кинул админские.

По настройке - нужно не только настроить, а и описать процесс настройки, набор нужных, чтобы это можно было воспросизводить. Давайте под это отдельную ишую заведём.

p.s. Ты занял, видимо, имя Shreks  =_=

**Comment by lipa44** [comment]
> p.s. Ты занял, видимо, имя Shreks =_=

Не, название у меня `shreks-webhooks-handler-test`

**Comment by lipa44** [comment]
cloded in #76
