### ISSUE TITLE
Интегрировать Application API в модуль хендлинга хуков

### ISSUE THREAD

**Issue by lipa44** [kysect/Shreks#32]
Необходимо интегрировать хендлинг хуков со **слоем приложения**, после того, как **слой приложения** будет готов.

## Tasks

- [x] #101
- [x] #133

**Comment by lipa44** [comment]
# Blocked by
* #14

**Comment by lipa44** [comment]
@FrediKats Не совсем понял, почему `blocked` убралось.

На данный момент в абстракциях CQRS у нас лежат Response модели, которые вместо сущностей возвращают гуиды и нет никакого API для **получения именно сущностей**, с которыми нужно работать _(например, получить ментора из базы по никнейму или хотя бы понять что такой ментор есть, и убедиться что команду можно обрабатывать)_

**Comment by FrediKats** [comment]
Разве для того, чтобы интегрировать гитхаб, нам не достаточно прописать нужные вызовы в медиаторе? Да, у нас нет хендлеров для этих команд, но на это заведены отдельные таски, вроде.

**Comment by lipa44** [comment]
> Разве для того, чтобы интегрировать гитхаб, нам не достаточно прописать нужные вызовы в медиаторе? Да, у нас нет хендлеров для этих команд, но на это заведены отдельные таски, вроде.

Достаточно. То что хендлеров нету - это ок. Просто у нас слишком мало CQRS комманд, они не покрывают тот функционал, который нужен для релизации хендлинга.

Банальный пример: 

1. Мне нужно получить Юзера/Ментора так или иначе из базы - сейчас у нас только получение гуида по нику. Как проверить, что написанный коммент сделан ментором и что его нужно обрабатывать?

Пока что я больше примеров не накину, тк это было первое, что мне пришло в голову когда я сел смотреть, и понял что нету даже этого...

Тут 2 варианта исхода событий:

1. Мы соберёмся и решим, какие нам нужны команды/квери для интеграции _(я предварительно сяду и распишу всё что нужно)_ и их реализует **кто-то**
2. Я сам сяду и напишу все эти команды сразу в ПР интеграции, раз уж хендлеры пока что не нужны и можно обойтись Command/Query моделями.

**Comment by lipa44** [comment]
blocked by #58

**Comment by FrediKats** [comment]
Обсудили с @darksidersstrife и поняли, что это не таска, а река, которая на много тасок поделилась.

**Comment by FrediKats** [comment]
От этой таски осталась реализация обработки фейла. Думаю, что это отдельная задача, а интеграция сделано в нужной мере.
