### ISSUE TITLE
Не удалётся смёрджить ячейки в заголовке из-за неправильного количества закреплённых строк

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#326]
Попытка обновить баллы падает с `Invalid requests[5].mergeCells: You can't merge frozen and non-frozen rows.`. В таблице имеем такое:

![image](https://user-images.githubusercontent.com/22368203/188410286-d0f0c819-0f0c-4f4c-85be-e3c5b972ce56.png)

Если руками попробовать смёрджить эти три ячейки, то получаем эту же ошибку.

**Comment by Mihinator3000** [comment]
Ну это просто логично, что мы A1:A3 не можем замержить, у нас не может быть ячейки разбитой freezed строчкой/столбцом, откуда же они взялись - не ясно

**Comment by FrediKats** [comment]
Выяснили, что это пользователи таблицы её вставили туда =_=
Бага переходит в разряд фичи - давайте научимся правильно перемещать эту строчку, чтобы:

- Было красиво с коробки
- Не допускать такой проблемы

**Comment by Mihinator3000** [comment]
Тогда это скорее идет в #308

**Comment by FrediKats** [comment]
Тогда закрываем как by design.
