### ISSUE TITLE
Проработать сценарий перевода PR в драфт студентом

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#38]
Случаются ситуации, когда студенту нужно уже закинутый PR пометить как "не готовый", чтобы он не попал в очередь и мог доработать, а не просто тратить время на сдачу. Вариант с использованием draft PR не подходит - не доступно в приватных организациях.

**Comment by lipa44** [comment]
Как вариант, можно поддержать команду аля `/to-draft` от лица метнтора в комментариях ПР

В целом, весь функционал, который нам так или иначе недоступен из-за ограничений ГХ, можно поддержать **как минимум** с помощью команд (по факту парсинга текста комментария и проверки пермишенов на совершение действия)

**Comment by FrediKats** [comment]
Хотелось бы, чтобы студенты могли свои PR тоже отмечать как драфт, чтобы лишний раз препода не тыкать.

**Comment by lipa44** [comment]
> Хотелось бы, чтобы студенты могли свои PR тоже отмечать как драфт, чтобы лишний раз препода не тыкать.

Не думаю, что с этим будут проблемы - тоже реализуемо. Главное - чтобы **слой приложения** мог обрабатывать перевод ПР в драфт _(убирание из очереди, насколько я понимаю)_ - тут мы снова упираемся в ограниченный набор CQRS комманд/кверей на данный момент (писао про это в #32)

**Comment by hrrrrustic** [comment]
>Как вариант, можно поддержать команду аля /to-draft

А зачем? Что мешает просто перевод в драфт хендлить и убирать из очереди?

**Comment by FrediKats** [comment]
То, что драфтов нет в приватных репо фри организаций.

**Comment by FrediKats** [comment]
Я же правильно понимаю, что в #189 в итоге это всё реализовано?

**Comment by ronimizy** [comment]
Да
