### ISSUE TITLE
Ошибка при использовании LookUp на листе "Баллы"

### ISSUE THREAD

**Issue by Mihinator3000** [kysect/Shreks#435]
При малом количестве лабораторных (около двух) формула LookUp почему-то выдает гитхаб пользователя, вместо суммы баллов за лабы
![image](https://user-images.githubusercontent.com/70411602/190868190-ca29f5c6-0e3d-445f-9dd7-7a61abaeeec3.png)

**Comment by FrediKats** [comment]
Тоже словил на тестовом стенде, где две лабы.
