### ISSUE TITLE
Решить проблему с параллельной записью в таблицы

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#47]
Нужно продумать ситуацию, когда мы будем пытаться из двух разных запросов написать что-то в гугл таблицу. Хотелось бы, чтобы был какой-то синк.

**Comment by Mihinator3000** [comment]
Я бы хотел попробовать это сделать, но не очень понимаю в каком вообще месте вызов обновления таблиц будет и откуда данные для них будут браться.

**Comment by FrediKats** [comment]
>  в каком вообще месте

Можно начать с логики создания сабмишена - https://github.com/kysect/Shreks/blob/master/Source/Application/Kysect.Shreks.Application.Handlers/Submissions/CreateSubmissionHandler.cs. После того, как создаётся новый сабмишен, мы должны добавить его в очередь и записать в таблицу.

Как я вижу реализацию этого хендлера с точки зрения генерации таблицы:

- Создаётся новый сабмит
- Вызывается какой-то метод _presenter.PrintQueue(...) и в него закидывается эта очередь (и видимо идентификатор Subject course чтобы определять таблицу)
- Достаются все актуальные сабмиты внутри него
- Формируются в определённую очередь (см. ишую 52)

При оценивании будет подобное:

- Проставляется / обновляется оценка
- Вызывается метод _presenter.PrintMarks(...) и аналогично прокидывается всё нужное
- Достаются данные внутри него

Какие проблемы нужно подумать и решить:

- Нам нужна логика получения данных об успеваемости студентов по определёному SubjectCourse, я так полагаю. Я, наверное, заведу на это ишую отдельно т.к. это блочит данную ишую
- Нам нужна такая же логика для получения уже построенной очереди. Нужно с @ronimizy засинкаться т.к. он реализацию очереди пилит.
- В какой-то момент для Subject course нужно будет впервые создать таблицу. Я бы предложил её очень нагло захардкодить и создать отдельную ишую на это (нам нужно будет в базе хранить, я думаю)

**Comment by Mihinator3000** [comment]
А вышеупомянутый _presenter где хранится должен? Вроде и не хэндлер, но и в гугл интеграцию не очень хочется.
Про создать таблицу имеется в виду прям spreadsheet? Я как-то думал, что это будет руками настраиваться

**Comment by FrediKats** [comment]
Это часть нашей интеграции с гуглом. Думаю, что там будет логика из дто переноса данных в таблицу и ничего более.

**Comment by FrediKats** [comment]
Ну а по созданию - 102.

**Comment by Mihinator3000** [comment]
У нас пока у курса нет ассоциации с таблицей, правильно понимаю?

**Comment by FrediKats** [comment]
Точно, нет. Можно в чате уточнить, но я точно не видел такого. Можешь тоже добавить заодно аналогично ассоциации с github организацией.
