### ISSUE TITLE
Формализовать список комманд, поддерживаемых в комментариях к ПР

### ISSUE THREAD

**Issue by lipa44** [kysect/Shreks#58]
> Имеются ввиду команды, которые можно будет вводить в комментарии к ПР.

Для полной интеграции с гитом очень хочется иметь:

1. Список всех комманд, которые мы будем обрабатывать, в формализованном виде (хотя бы `Enum`) в слое `Domain`
   - Например: `/to-draft`, `/approved` и т.п
2. CQRS абстракции, которые будут уметь эти команды обрабатывать в слое `Application` (в любом виде)

**Comment by FrediKats** [comment]
Апнул т.к. блочит другую таску важную.

**Comment by FrediKats** [comment]
Команды описаны тут - https://github.com/kysect/Shreks/blob/master/Docs/GithubCommand.md

**Comment by FrediKats** [comment]
Модели для CQRS тут - https://github.com/kysect/Shreks/tree/master/Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/

Реализация, которую написал и откатил Библетун, тут - b4ba4c66f0725df5755294104fae4b9b9012feab

Если я правильно всё понял, то в рамках ишуи нужно вернуть реализацию и всё будет ок.

**Comment by FrediKats** [comment]
link #30

**Comment by lipa44** [comment]
> Модели для CQRS тут - https://github.com/kysect/Shreks/tree/master/Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/
> 
> Реализация, которую написал и откатил Библетун, тут - [b4ba4c6](https://github.com/kysect/Shreks/commit/b4ba4c66f0725df5755294104fae4b9b9012feab)
> 
> Если я правильно всё понял, то в рамках ишуи нужно вернуть реализацию и всё будет ок.

Не, то что нет хендлеров - это вообще не важно.

Не хватает кверей и комманд, которые мы должны отправлять в медиатор из хендлинга хуков.

## Кейсы: 

### К нам приходит комментарий в ПР.

1. Изначально нужно понять, **кто отправил команду** в комментарии - **ментор или студент**, для того, чтобы не выполнять команды, на которые у отправителя нет пермишена

    - Необходимо реализовать IRequest, который будет принимать имя отправителя или любой другой идентификатор и возвращать его роль в системе *
    - _*Либо делать эту проверку на уровне приложения, пробрасывая туда **ВСЕ** комментарии, нагружая лишний раз систему_

2. Комментарий надо распарсить и понять должны ли мы его обрабатывать.

    - Надо предоставить какой-то сервис на уровне приложения для того, чтобы это делать не на стороне хендлинга _(IRequest или тупо сервис - не важно, **нужно, чтобы мы умели понять, является ли комментарий коммандой или тупо текстом**)_
    - В зависимости от реализации сервиса необходимо сделать IRequest'ы для каждой из поддерживаемых нами команд, который будет принимать её аргументы (это +- есть, надо только уметь распарсить текст в комманду чтобы кинуть в медиатор нужный IRequest)

> Пока что это всё, что я надумал по этому поводу

## Итог

Для начала интеграции хуков со слоем приложения нам необходимо объявить как минимм **2 абстракции**:

1. Получение роли юзера в системе - `GetUserRoleBy...Query`

<img width="856" alt="image" src="https://user-images.githubusercontent.com/82240296/183257787-233c5496-fcd5-499d-b24d-ef6e9078dd2f.png">

Вот моделька отправителя, можно проверять по любому из её полей или их совокупности

2. Парсинг текста в команду - `ParseCommentToCommand..., returns DomainCommandEnum`

**Comment by FrediKats** [comment]
link #65
