### ISSUE TITLE
Реализовать возможность авторизоваться в Github и получить username

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#69]

**Comment by FrediKats** [comment]
Авторизация в гитхабе всегда боль. Потыкайте варианты, посмотрите, что можем получить. И потом будем обсуждать.

**Comment by darksidersstrife** [comment]
https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps#web-application-flow
Кнопочка должна вести на https://github.com/login/oauth/authorize, в который прокидывается client_id нашей аппы
Дальше юзер жмет "да да, дайте этой аппе что ей нужно", его редиректит на эндпоинт, в котором мы добавляем ассоациацию (его надо установить в настройках аппы и еще прокидывать в параметрах)

**Comment by darksidersstrife** [comment]
Ну, в эндпоинте надо будет заменить полученный код на юзер токен и сходить в https://docs.github.com/en/rest/users/users#get-the-authenticated-user
