### ISSUE TITLE
Доработки по хранению Pull request в сабмишене

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#72]
Нужно убедиться, что у нас реализованы:

- Логика сохранения информации о PR при создании сабмишен
- Возможность найти сабмишен (ы?) по PR

Заодно бы подумать о том, чтобы в сабмишене хранить не payload, а ассоциации и явно прописать, что там лежит PR.

**Comment by darksidersstrife** [comment]
Нам нужно находить активный сабмишен по пру - то есть последний неоцененный
Кажется удалять ассоциации при оценивании все же не хочется (слишком много где это протаскивать), так что надо будет написать запросик, чтобы не брать оцененные и взять последний (если каким-то образом у нас окажется больше 1 неоцененного, чего быть не должно конечно)
