### ISSUE TITLE
Реализовать логику получения успеваемости курса

### ISSUE THREAD

**Issue by FrediKats** [kysect/Shreks#95]
Нам нужно из базы доставать данные об успеваемости и конвертировать в удобный для генерации в таблице формат. Предположительно, сначала можем сделать кверю, которая бы по subjectCourseId возвращала что-то в духе:

```csharp
public record SubjectCourseMarks(List<string> Assignments, List<GroupMarks> Groups);
public record GroupMarks(string GroupName, List<StudentMarks> Students);
public record StudentMarks(string FullName, List<AssignmentMark> Marks);
public record AssignmentMark(double Points, double ExtraPoints, DateTime submissionDate);
```
ref #47

**Comment by FrediKats** [comment]
@Mihinator3000, возьмёшь, чтобы подготовить разблокировать 47?

**Comment by Mihinator3000** [comment]
Так то не против, но снова пара вопросов.
Во-первых, зачем нам рекорды, представленные выше? У нас же вроде уже есть необходимые структуры для таблиц, находящиеся в Kysect.Shreks.Application.Abstractions.Google.
Во-вторых, где эту логику реализовывать надо?

**Comment by FrediKats** [comment]
Рекордами я пытался описать как +/- какой dto должна быть, чтобы её можно было закинуть в алгоритм генерации таблицы и этого было бы достаточнго. Если просто вернуть данные из таблицы в том виде, в котором они есть, то на стороне генератор таблицы нужно будет данные доприводить в нужный формат (тот же твой вопрос про несколько сабмишенов и их обработку).

Я бы начал с того, чтобы мы в Application.Abstraction описали кверю и в Application.Handlers хендлер для получения.
Ну и для первой итерации можно упростить - брать баллы только за последний сабмит и игнорировать дедлайн полиси. Сначала получим хнедлер, чтобы его можно заюзать, а дедлайны привязать сможем потом, чтобы сейчас не блочило.

**Comment by Mihinator3000** [comment]
У нас просто таблица баллов нацелена чтобы печатать сразу всех студентов, без разделения на группы, а так единственное что мы форматируем это полное имя студента. При этом AssignmentMark все равно должно в себе хранить Assignmnent. Как-то не очень много смысла вижу в изменении структуры, может я не улавливаю что-то

**Comment by FrediKats** [comment]
> У нас просто таблица баллов нацелена чтобы печатать сразу всех студентов, без разделения на группы,

А, хм. Почему-то у меня в голове было деление. Не знаю почему. Тогда да, ты прав, можно упостить.
